### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by Megumemed** [IlluminatiFish/VPNDetector#1]
Lines 39 in VPNDetector

 have incorrect indentation causing the script to fail.
![image](https://user-images.githubusercontent.com/38935748/105841758-0d3d7d00-5fcd-11eb-84c2-2df19ec725ef.png)

Resolved by adding a space on line 39
![image](https://user-images.githubusercontent.com/38935748/105841808-27775b00-5fcd-11eb-91f5-3d48526a12f4.png)

**Comment by IlluminatiFish** [comment]
Issue resolved
